version: '3'
services:
  web:
    build: ./
    ports:
      - "80"
    networks:
      fixedip:
        ipv4_address: 172.21.0.100
networks:
  fixedip:
      ipam:
        driver: default
        config:
          - subnet: 172.21.0.0/16
